# This is a basic workflow to help you get started with Actions

name: Weather Update

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-weather:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run a multiline script
      - name: Run a multi-line script
        run: |
          ls
          weather=$(awk -F\, '{print $1}' usap.csv  | tr "\n" "," | sed 's/^/curl wttr.in\/{/' | sed 's/,$/}?format=1/') && sed '1d; n; d' <($weather) > temp.csv && paste -d ',' temp.csv usap.csv | sed '1 s/^/deg,iata,name,city,state,country,lat,lon\n/' > weathernow.csv && rm temp.csv
          ls
      - uses: jasineri/simple-push-action@v1
        with:
           # Files pattern to add, wildcards supported
           # Optional, default: ./*.*
           file_pattern: weathernow.csv
          
